/**
 * FreeLang Nexus 2 — 통합 코드 생성기
 *
 * 트랜스파일된 함수들을 하나의 unified.fl 파일로 생성
 */

import { TranspiledResult } from '../transpiler/main';

export function generateUnifiedCode(ast: any, transpiledResult: TranspiledResult): string {
  const lines: string[] = [];

  // 헤더
  lines.push('// AUTO-GENERATED by FreeLang Nexus 2');
  lines.push('// This file transpiles multiple languages to FreeLang v9');
  lines.push('');
  lines.push('// ──────────────────────────────────────────────────────');
  lines.push('// Transpiled Functions');
  lines.push('// ──────────────────────────────────────────────────────');
  lines.push('');

  // 트랜스파일된 함수들
  for (const fn of transpiledResult.functions) {
    lines.push(`// [${fn.lang.toUpperCase()}] ${fn.name}`);
    lines.push(`${(fn as any).flv9Sig} {`);
    lines.push(`  ${(fn as any).flv9Body}`);
    lines.push('}');
    lines.push('');
  }

  // V 오케스트레이터 코드
  if (transpiledResult.vCode.trim()) {
    lines.push('// ──────────────────────────────────────────────────────');
    lines.push('// V Orchestrator (from original .fl)');
    lines.push('// ──────────────────────────────────────────────────────');
    lines.push('');
    lines.push(transpiledResult.vCode);
  }

  return lines.join('\n');
}

export default generateUnifiedCode;
