/**
 * FreeLang Nexus 2 — S-expression 코드 생성기
 *
 * 트랜스파일된 함수들을 FreeLang v9 S-expression 포맷으로 생성
 */

import { TranspiledResult } from '../transpiler/main';
import { ExportedFunction, mapType, transpileBody } from '../transpiler/base';

/**
 * S-expression으로 변환된 함수 본체
 */
function toSExpression(lang: string, body: string): string {
  let result = body.trim();

  // 1. return 문 제거
  result = result.replace(/^\s*return\s+/, '').replace(/;$/, '');

  // 2. 언어별 body 변환 (operator를 S-expression으로)
  result = transpileBody(lang, result);

  // 3. 기본 연산자를 S-expression으로 변환
  result = convertToSExpression(result);

  return result;
}

/**
 * C-like 표현을 S-expression으로 변환
 * 예: "x * 2" → "(* $x 2)"
 *     "a + b" → "(+ $a $b)"
 */
function convertToSExpression(expr: string): string {
  let result = expr.trim();

  // 세미콜론 제거
  result = result.replace(/;$/, '');

  // Step 1: 변수명 앞에 $ 추가 (문자로 시작하는 identifier, 문자열 외부)
  result = addDollarPrefix(result);

  // Step 2: 이항 연산자를 S-expression으로 변환
  result = convertBinaryOps(result);

  // Step 3: 함수 호출을 S-expression으로 변환
  result = convertFunctionCalls(result);

  return result;
}

/**
 * 변수 이름 앞에 $ 추가
 * 숫자 리터럴, 문자열, 예약어는 제외
 */
function addDollarPrefix(expr: string): string {
  // 문자열 내부는 보호 (간단히: "..."와 '...'는 그대로 둠)
  let result = '';
  let inString = false;
  let stringChar = '';

  for (let i = 0; i < expr.length; i++) {
    const char = expr[i];

    // 문자열 시작/종료 감지
    if ((char === '"' || char === "'") && (i === 0 || expr[i - 1] !== '\\')) {
      if (!inString) {
        inString = true;
        stringChar = char;
        result += char;
      } else if (char === stringChar) {
        inString = false;
        result += char;
      } else {
        result += char;
      }
    } else if (inString) {
      // 문자열 내부이면 그대로
      result += char;
    } else {
      // 문자열 외부: 변수명 앞에 $ 추가
      result += char;
    }
  }

  // 정규식: 단어 경계에서 이미 $가 없는 identifier에 $ 추가
  result = result.replace(/\b([a-zA-Z_]\w*)\b/g, (match) => {
    if (/^\d|^return$|^if$|^while$|^let$|^fn$|^println$|^print$|^true$|^false$/.test(match)) {
      return match;
    }
    if (match.startsWith('$')) {
      return match;
    }
    return '$' + match;
  });

  return result;
}

/**
 * 이항 연산자를 S-expression으로 변환
 */
function convertBinaryOps(expr: string): string {
  let result = expr;

  // 비교 연산자 (길이 긴 것부터)
  result = result.replace(/(\$\w+)\s*>=\s*(\$?\w+)/g, '(>= $1 $2)');
  result = result.replace(/(\$\w+)\s*<=\s*(\$?\w+)/g, '(<= $1 $2)');
  result = result.replace(/(\$\w+)\s*==\s*(\$?\w+)/g, '(= $1 $2)');
  result = result.replace(/(\$\w+)\s*!=\s*(\$?\w+)/g, '(!= $1 $2)');
  result = result.replace(/(\$\w+)\s*>\s*(\$?\w+)/g, '(> $1 $2)');
  result = result.replace(/(\$\w+)\s*<\s*(\$?\w+)/g, '(< $1 $2)');

  // 산술 연산자 (higher precedence 먼저)
  result = result.replace(/(\$?\w+)\s*\*\s*(\$?\w+)/g, '(* $1 $2)');
  result = result.replace(/(\$?\w+)\s*\/\s*(\$?\w+)/g, '(/ $1 $2)');
  result = result.replace(/(\$?\w+)\s*\+\s*(\$?\w+)/g, '(+ $1 $2)');
  result = result.replace(/(\$?\w+)\s*-\s*(\$?\w+)/g, '(- $1 $2)');

  return result;
}

/**
 * 함수 호출을 S-expression으로 변환
 */
function convertFunctionCalls(expr: string): string {
  let result = expr;

  // println(...) → (println ...)
  result = result.replace(/println\s*\(\s*([^)]*)\s*\)/g, (match, args) => {
    const trimmedArgs = args.trim();
    return trimmedArgs ? `(println ${trimmedArgs})` : '(println)';
  });

  // print(...) → (println ...)
  result = result.replace(/print\s*\(\s*([^)]*)\s*\)/g, (match, args) => {
    const trimmedArgs = args.trim();
    return trimmedArgs ? `(println ${trimmedArgs})` : '(println)';
  });

  return result;
}

/**
 * 함수를 S-expression [FUNC ...] 블록으로 생성
 */
function generateFunctionBlock(fn: ExportedFunction): string[] {
  const lines: string[] = [];
  const mappedReturnType = mapType(fn.lang, fn.returnType);

  // 주석 (언어 표시)
  lines.push(`; [${fn.lang.toUpperCase()}] ${fn.name}`);

  // FUNC 블록 시작
  lines.push(`[FUNC ${fn.name}`);

  // :params 섹션
  const paramNames = fn.params.map(p => `$${p.name}`).join(' ');
  lines.push(`  :params [${paramNames}]`);

  // :return 섹션 (void가 아닐 때만)
  if (fn.returnType !== 'void') {
    lines.push(`  :return ${mappedReturnType}`);
  }

  // :body 섹션 (S-expression으로 변환된 본체)
  const sExprBody = toSExpression(fn.lang, fn.body);
  lines.push(`  :body ${sExprBody}`);

  // FUNC 블록 종료
  lines.push(']');

  return lines;
}

/**
 * 통합 코드 생성: 모든 트랜스파일된 함수를 하나의 unified.fl 파일로
 */
export function generateUnifiedCode(ast: any, transpiledResult: TranspiledResult): string {
  const lines: string[] = [];

  // 헤더 (Lisp 스타일 주석)
  lines.push('; AUTO-GENERATED by FreeLang Nexus 2');
  lines.push('; Transpiled from Rust/Go/C/Python to FreeLang v9 S-expression');
  lines.push('');

  // 트랜스파일된 함수들
  for (const fn of transpiledResult.functions) {
    const funcLines = generateFunctionBlock(fn as ExportedFunction);
    lines.push(...funcLines);
    lines.push('');
  }

  // V 오케스트레이터 코드 (있으면)
  if (transpiledResult.vCode.trim()) {
    lines.push('; ─ V Orchestrator Code (from original .fl) ─');
    lines.push(transpiledResult.vCode);
  }

  return lines.join('\n');
}

export default generateUnifiedCode;
